# Swarm cluster with fast EBS volumes for storage.
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "swarm"
spec:
  configuration:
    clusters:
      - name: "example"
        layout:
          replicas:
          - templates:
              podTemplate: replica
              volumeClaimTemplate: storage
          shardsCount: 4
    zookeeper:
        nodes:
        - host: keeper-keeper
          port: 2181
    users:
      cache_enabled/networks/ip: "::/0"
      cache_enabled/password: topsecret
      cache_enabled/profile: default 
    profiles:
      default/enable_filesystem_cache: 0
      #default/enable_filesystem_cache_log: 1
      default/filesystem_cache_name: "s3_parquet_cache"
      cache_enabled/enable_filesystem_cache: 1
      #cache_enabled/enable_filesystem_cache_log: 1
      cache_enabled/filesystem_cache_name: "s3_parquet_cache"
    files:
      config.d/remote_servers.xml: |
        <clickhouse>
          <allow_experimental_cluster_discovery>1</allow_experimental_cluster_discovery>
          <remote_servers>
            <!-- Swarm cluster built using remote discovery. -->
            <swarm>
              <discovery>
                <path>/clickhouse/discovery/swarm</path>
                <secret>secret_key</secret>
              </discovery>
            </swarm>
          </remote_servers>
        </clickhouse>
      config.d/filesystem_cache.xml: |
        <clickhouse>
          <filesystem_caches>
            <s3_parquet_cache>
              <path>/var/lib/clickhouse/s3_parquet_cache</path>
              <max_size>50Gi</max_size>
            </s3_parquet_cache>
          </filesystem_caches>
        </clickhouse>
  templates:
    podTemplates:
      - name: replica
        spec:
          nodeSelector:
            node.kubernetes.io/instance-type: m6i.xlarge
          tolerations:
          # Run on clickhouse nodes that are dedicated to swarm servers.   
          - key: "antalya"
            operator: "Equal"
            value: "swarm"
            effect : "NoSchedule"
          - key: "dedicated"
            operator: "Equal"
            value: "clickhouse"
            effect : "NoSchedule"
          affinity:
            # Specify Pod anti-affinity to Pods with the same label "/app" on the same "hostname"
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: "clickhouse.altinity.com/app"
                        operator: In
                        values:
                          - "chop"
                  topologyKey: "kubernetes.io/hostname"
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:25.3.3.20186.altinityantalya
    volumeClaimTemplates:
      - name: storage
        # Uncomment for prod systems. You will then need to delete PVCs manually. 
        # reclaimPolicy: Retain
        spec:
          storageClassName: gp3-encrypted
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 75Gi
